### ISSUE TITLE
Переписать фильтр через ассоциативный массив/объект

### ISSUE THREAD

**Issue by x-alice-x** [egal/framework-npm-package#19]
В настоящем, чтобы автоматизировать построение массива фильтров, необходимо рекурсивно проходится по массиву и проверять филды на соответствие тому, что нужно заменить или удалить. Если бы к нужному нам филду можно было бы обращаться по ключу, не было бы необходимости рекурсивного прохождения.

**Comment by Yulya-Yu** [comment]
закрываю, т.к. для третьей версии не актуально.
