### ISSUE TITLE
Добавить возможность верификации электронной почты

### ISSUE THREAD

**Issue by srrmstk** [egal/framework-npm-package#42]
Следуя философии Egal, "из коробки" должно быть доступно любое повторяющееся действие. Верификация почты - та вещь, которая может применятся на большом количестве проектов, поэтому хотелось бы, чтобы этот механизм был реализован и на фронте, и на бэке егала. Как вариант - на клиенте в AuthConstructor зашить следующие экшны:
* generateCode (auth/VerifyCode/generateCode) (атрибуты: email) - экшн генерирует код, который добавляет запись в бд
* checkCode (auth/VerifyCode/checkCode) (атрибуты: email, user_code) - экшн проверки введенного пользователем кода с кодом на бэке. При успехе можно продолжить регистрацию, при ошибке - падает exception.
* в registerByEmailAndPassword (auth/User/registerByEmailAndPassword) дополнительно прокидывать password_confirmation и code (который ввел пользователь).

**Comment by Yulya-Yu** [comment]
Все эти этапы слишком специфичны чтобы прописывать их в Egal, для этого можно использовать кастомный action или переопределить класс авторизации в проекте.
