### ISSUE TITLE
К кастомным экшнам не добавляются фильтры и пагинация

### ISSUE THREAD

**Issue by srrmstk** [egal/framework-npm-package#82]
При создании кастомного экшна и добавлении фильтров/пагинации, они не добавляются в реквест 

Пример запроса:
```
action
    .custom(_, _, _, {
        data: "",
      })
    .setPagination(10, 1)
    .call();
```

Ожидаемый результат:
```
parameters: {
    attributes: {
        data: ""
    },
    pagination: {
        perPage: 10,
        page: 1
    }
}
```
Реальный результат:
```
parameters: {
    attributes: {
        data: ""
    }
}
```
Возможно это не работает еще и withs, не проверял

**Comment by Yulya-Yu** [comment]
Добавлено в релизе [v2.0.9-react-native](https://github.com/egal/framework-npm-package/releases/tag/v2.0.9-react-native)

**Comment by srrmstk** [comment]
@Yulya-Yu  🚩 2
